#ifndef __INC_METIN2_COMMON_DEFINES_H__
#define __INC_METIN2_COMMON_DEFINES_H__

#define ENABLE_PLAYER_PER_ACCOUNT5
#define ENABLE_PORT_SECURITY

enum eCommonDefines {
	MAP_ALLOW_LIMIT = 32, // 32 default
};


#define ENABLE_WOLFMAN_CHARACTER
#ifdef ENABLE_WOLFMAN_CHARACTER
#define USE_MOB_BLEEDING_AS_POISON
#define USE_MOB_CLAW_AS_DAGGER
//#define USE_ITEM_BLEEDING_AS_POISON
//#define USE_ITEM_CLAW_AS_DAGGER
//#define USE_WOLFMAN_STONES
//#define USE_WOLFMAN_BOOKS
#endif

#define ENABLE_MOUNT_COSTUME_SYSTEM
#define ENABLE_ACCE_COSTUME_SYSTEM
#define ENABLE_EXTEND_INVEN_SYSTEM
#define ENABLE_WEAPON_COSTUME_SYSTEM

//#define ENABLE_MAGIC_REDUCTION_SYSTEM
//#ifdef ENABLE_MAGIC_REDUCTION_SYSTEM
//#define USE_MAGIC_REDUCTION_STONES
//#endif
#endif

#define ENABLE_DICE_SYSTEM
#define EFFECT_TITLE_SYSTEM
#define ENABLE_GEM_SYSTEM
#define ENABLE_AURA_COSTUME_SYSTEM
#define ENABLE_NEW_GYEONGGONG_SKILL
#define ENABLE_SPECIAL_INVENTORY
#define ENABLE_INVENTORY_SORT
#define ENABLE_MULTILANGUAGE